group 'sq.flutter.tflite'
version '1.0-SNAPSHOT'

apply plugin: 'com.android.library'

android {
    namespace 'sq.flutter.tflite'
    compileSdk 36

    defaultConfig {
        minSdkVersion 19
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }
    lintOptions {
        disable 'InvalidPackage'
    }
}

repositories {
    google()
    mavenCentral()
}

dependencies {
    implementation 'org.tensorflow:tensorflow-lite:+'
    implementation 'org.tensorflow:tensorflow-lite-gpu:+'
}
